import type { ThemeDefinition, ThemeName } from '../../types/typst';

export const THEMES: Record<ThemeName, ThemeDefinition> = {
  'modern-clean': {
    name: 'modern-clean',
    displayName: 'Modern Clean',
    fontFamily: 'Liberation Sans',
    headingFontFamily: 'Liberation Sans',
    primaryColor: '#2563EB',
    secondaryColor: '#64748B',
    accentColor: '#3B82F6',
    headerBackground: '#F1F5F9',
    headerTextColor: '#0F172A',
    zebraBackground: '#F8FAFC',
    borderColor: '#E2E8F0',
    textColor: '#334155',
    kpiBackground: '#F8FAFC',
    kpiBorderColor: '#CBD5E1',
    kpiAccentColor: '#2563EB',
    noteBackground: '#FEF3C7',
    noteBorderColor: '#F59E0B',
    tableStroke: '0.5pt + rgb("e2e8f0")',
    margins: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' },
    cellPadding: { x: '4pt', y: '3pt' },
    baseFontSize: 8.5,
  },
  'executive-serif': {
    name: 'executive-serif',
    displayName: 'Executive Serif',
    fontFamily: 'Libertinus Serif',
    headingFontFamily: 'Libertinus Serif',
    primaryColor: '#1E293B',
    secondaryColor: '#475569',
    accentColor: '#94A3B8',
    headerBackground: '#1E293B',
    headerTextColor: '#FFFFFF',
    zebraBackground: '#F8FAFC',
    borderColor: '#CBD5E1',
    textColor: '#1E293B',
    kpiBackground: '#F1F5F9',
    kpiBorderColor: '#94A3B8',
    kpiAccentColor: '#1E293B',
    noteBackground: '#F8FAFC',
    noteBorderColor: '#64748B',
    tableStroke: '0.5pt + rgb("cbd5e1")',
    margins: { top: '18mm', bottom: '18mm', left: '18mm', right: '18mm' },
    cellPadding: { x: '4pt', y: '3.5pt' },
    baseFontSize: 8.5,
  },
  'compact-ledger': {
    name: 'compact-ledger',
    displayName: 'Compact Ledger',
    fontFamily: 'Liberation Sans',
    headingFontFamily: 'Liberation Sans',
    primaryColor: '#0F172A',
    secondaryColor: '#334155',
    accentColor: '#475569',
    headerBackground: '#E2E8F0',
    headerTextColor: '#0F172A',
    zebraBackground: '#F1F5F9',
    borderColor: '#94A3B8',
    textColor: '#0F172A',
    kpiBackground: '#E2E8F0',
    kpiBorderColor: '#64748B',
    kpiAccentColor: '#0F172A',
    noteBackground: '#F1F5F9',
    noteBorderColor: '#475569',
    tableStroke: '0.5pt + rgb("94a3b8")',
    margins: { top: '10mm', bottom: '10mm', left: '10mm', right: '10mm' },
    cellPadding: { x: '3pt', y: '2pt' },
    baseFontSize: 7.5,
  },
  'emerald-report': {
    name: 'emerald-report',
    displayName: 'Emerald Report',
    fontFamily: 'Liberation Sans',
    headingFontFamily: 'Liberation Sans',
    primaryColor: '#059669',
    secondaryColor: '#047857',
    accentColor: '#10B981',
    headerBackground: '#ECFDF5',
    headerTextColor: '#064E3B',
    zebraBackground: '#F0FDF4',
    borderColor: '#A7F3D0',
    textColor: '#064E3B',
    kpiBackground: '#ECFDF5',
    kpiBorderColor: '#6EE7B7',
    kpiAccentColor: '#059669',
    noteBackground: '#ECFDF5',
    noteBorderColor: '#10B981',
    tableStroke: '0.5pt + rgb("a7f3d0")',
    margins: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' },
    cellPadding: { x: '4pt', y: '3pt' },
    baseFontSize: 8.5,
  },
  'monochrome-pure': {
    name: 'monochrome-pure',
    displayName: 'Monochrome Pure',
    fontFamily: 'Liberation Sans',
    headingFontFamily: 'Liberation Sans',
    primaryColor: '#000000',
    secondaryColor: '#555555',
    accentColor: '#000000',
    headerBackground: '#E5E5E5',
    headerTextColor: '#000000',
    zebraBackground: '#F5F5F5',
    borderColor: '#000000',
    textColor: '#000000',
    kpiBackground: '#FAFAFA',
    kpiBorderColor: '#000000',
    kpiAccentColor: '#000000',
    noteBackground: '#FAFAFA',
    noteBorderColor: '#000000',
    tableStroke: '0.5pt + rgb("000000")',
    margins: { top: '15mm', bottom: '15mm', left: '15mm', right: '15mm' },
    cellPadding: { x: '4pt', y: '3pt' },
    baseFontSize: 8.5,
  },
};

export function getTheme(theme?: ThemeName | ThemeDefinition | string): ThemeDefinition {
  if (!theme) {
    return THEMES['modern-clean'];
  }

  if (typeof theme === 'object' && theme !== null && 'name' in theme && 'primaryColor' in theme) {
    return theme as ThemeDefinition;
  }

  if (typeof theme === 'string' && theme in THEMES) {
    return THEMES[theme as ThemeName];
  }

  return THEMES['modern-clean'];
}
