import type {
  LayoutIR,
  DocumentSection,
  TableSection,
  KpiGridContent,
  TextSectionContent,
  PageSizeType,
} from '../../types/layout-ir';
import type { TypstGeneratorOptions, ThemeDefinition } from '../../types/typst';
import { getTheme } from './themes';
import { escapeTypst } from './typst-escaper';

/**
 * Maps PageSizeType to Typst paper string.
 */
function mapPaperSize(size?: PageSizeType): string {
  switch (size) {
    case 'a3':
      return 'a3';
    case 'a5':
      return 'a5';
    case 'letter':
      return 'us-letter';
    case 'legal':
      return 'us-legal';
    case 'a4':
    default:
      return 'a4';
  }
}

function resolveMargins(
  theme: ThemeDefinition,
  marginPreset?: 'compact' | 'normal' | 'spacious',
  isLandscape?: boolean
): { top: string; bottom: string; left: string; right: string } {
  if (marginPreset === 'compact') {
    return { top: '18pt', bottom: '18pt', left: '18pt', right: '18pt' };
  }
  if (marginPreset === 'spacious') {
    return { top: '54pt', bottom: '54pt', left: '54pt', right: '54pt' };
  }
  if (isLandscape) {
    return { top: '28pt', bottom: '28pt', left: '28pt', right: '28pt' };
  }
  return theme.margins;
}

/**
 * Generates modern Typst 0.11+ source markup from a LayoutIR document model.
 */
export function generateTypstDocument(
  layout: LayoutIR,
  options?: TypstGeneratorOptions
): string {
  const theme: ThemeDefinition = getTheme(options?.theme || layout.globalStyles.theme);
  const pageSize = options?.pageSize || layout.globalStyles.pageSize || 'a4';
  const orientation = options?.orientation || layout.globalStyles.orientation || 'portrait';
  const paper = mapPaperSize(pageSize);
  const isFlipped = orientation === 'landscape';
  const baseFontSize = options?.baseFontSize || layout.globalStyles.baseFontSize || (layout.sections.length > 5 ? 7.6 : theme.baseFontSize || 8.5);
  const showPageNumbers = options?.showPageNumbers !== false;
  const repeatTableHeaders = options?.repeatTableHeaders !== false;
  const marginPreset = options?.marginPreset;
  const layoutMode = options?.layoutMode || 'balanced';
  const margins = resolveMargins(theme, marginPreset, isFlipped);

  const docTitle = options?.headerTitle || layout.title || '';
  const escapedDocTitle = escapeTypst(docTitle);

  const lines: string[] = [];

  // Page setup with Typst 0.11+ context expressions
  lines.push('// Generated by Sheet-to-Art Typst Engine');
  lines.push('#set page(');
  lines.push(`  paper: "${paper}",`);
  lines.push(`  flipped: ${isFlipped ? 'true' : 'false'},`);
  lines.push(`  margin: (top: ${margins.top}, bottom: ${margins.bottom}, left: ${margins.left}, right: ${margins.right}),`);

  // Header context block (visible from page 2 onwards)
  if (docTitle || showPageNumbers) {
    lines.push('  header: context if here().page() > 1 [');
    lines.push('    #grid(');
    lines.push('      columns: (1fr, auto),');
    lines.push(`      align(left + bottom)[#text(size: 6.8pt, fill: rgb("${theme.secondaryColor}"))[${escapedDocTitle}]],`);
    lines.push(`      align(right + bottom)[#text(size: 6.8pt, fill: rgb("${theme.secondaryColor}"))[Page #counter(page).display()]]`);
    lines.push('    )');
    lines.push('    #v(1.5pt)');
    lines.push(`    #line(length: 100%, stroke: 0.5pt + rgb("${theme.borderColor}"))`);
    lines.push('  ],');
  }

  // Footer context block
  if (showPageNumbers) {
    lines.push('  footer: context align(center)[');
    lines.push(`    #text(size: 7pt, fill: rgb("${theme.secondaryColor}"))[Page #counter(page).display()]`);
    lines.push('  ]');
  }

  lines.push(')');
  lines.push('');

  // Global typography & paragraph styling
  const leading = layoutMode === 'compact' ? '0.40em' : '0.45em';
  lines.push(`#set text(font: "${theme.fontFamily}", size: ${baseFontSize}pt, fill: rgb("${theme.textColor}"))`);
  lines.push(`#set par(justify: false, leading: ${leading})`);
  lines.push('');

  // Document Title Banner (Page 1)
  if (docTitle) {
    lines.push('#block(');
    lines.push('  width: 100%,');
    lines.push('  inset: (bottom: 4pt),');
    lines.push(`  stroke: (bottom: 1.5pt + rgb("${theme.primaryColor}")),`);
    lines.push('  [');
    lines.push(`    #text(size: 11pt, weight: "bold", fill: rgb("${theme.primaryColor}"))[${escapedDocTitle}]`);
    lines.push('  ]');
    lines.push(')');
    lines.push('#v(4pt)');
    lines.push('');
  }

  // Render Document Sections
  for (let sIdx = 0; sIdx < layout.sections.length; sIdx++) {
    const section = layout.sections[sIdx] as DocumentSection;

    if (sIdx > 0) {
      lines.push('#v(4.5pt)');
    }

    if (section.type === 'kpi-grid') {
      renderKpiSection(section, theme, lines);
    } else if (section.type === 'table') {
      renderTableSection(section, theme, lines, repeatTableHeaders, layoutMode);
    } else if (section.type === 'text') {
      renderTextSection(section, theme, lines);
    }
  }

  return lines.join('\n');
}

/**
 * Renders a KPI metrics summary / checkpoint grid.
 */
function renderKpiSection(
  section: DocumentSection,
  theme: ThemeDefinition,
  lines: string[]
): void {
  const content = section.content as KpiGridContent;
  if (!content || !content.items || content.items.length === 0) return;

  if (section.title) {
    lines.push(`#heading(level: 2, numbering: none)[#text(size: 8.5pt, weight: "bold", fill: rgb("${theme.primaryColor}"))[${escapeTypst(section.title)}]]`);
    lines.push('#v(2pt)');
  }

  const numCols = content.columns || Math.min(content.items.length, 5) || 2;
  const colSpec = Array(numCols).fill('1fr').join(', ');

  lines.push('#block(');
  lines.push('  width: 100%,');
  lines.push('  breakable: false,');
  lines.push('  [');
  lines.push('    #grid(');
  lines.push(`      columns: (${colSpec}),`);
  lines.push('      gutter: 4pt,');

  for (const item of content.items) {
    lines.push('      block(');
    lines.push(`        fill: rgb("${theme.kpiBackground}"),`);
    lines.push(`        stroke: 0.5pt + rgb("${theme.kpiBorderColor}"),`);
    lines.push('        radius: 3pt,');
    lines.push('        inset: (x: 5pt, y: 3.5pt),');
    lines.push('        width: 100%,');
    lines.push('        [');
    lines.push(`          #text(size: 6.5pt, weight: "medium", fill: rgb("${theme.secondaryColor}"))[${escapeTypst(item.label)}]`);
    lines.push('          #v(1pt)');
    lines.push(`          #text(size: 8pt, weight: "bold", fill: rgb("${theme.kpiAccentColor}"))[${escapeTypst(item.value)}]`);
    if (item.change) {
      lines.push('          #v(1pt)');
      lines.push(`          #text(size: 6.2pt, fill: rgb("${theme.secondaryColor}"))[${escapeTypst(item.change)}]`);
    }
    lines.push('        ]');
    lines.push('      ),');
  }

  lines.push('    )');
  lines.push('  ]');
  lines.push(')');
}

/**
 * Renders a data table with repeating header and zebra striping.
 */
function renderTableSection(
  section: DocumentSection,
  theme: ThemeDefinition,
  lines: string[],
  repeatHeaders: boolean = true,
  layoutMode: string = 'balanced'
): void {
  const content = section.content as TableSection;
  if (!content || !content.columns || content.columns.length === 0) return;

  if (section.title) {
    lines.push(`#heading(level: 2, numbering: none)[#text(size: 8.5pt, weight: "bold", fill: rgb("${theme.primaryColor}"))[${escapeTypst(section.title)}]]`);
    lines.push('#v(2pt)');
  }

  const columns = content.columns;
  const colWidths = columns.map(c => {
    const w = c.suggestedWidth || c.minWidth || 50;
    return `${w.toFixed(1)}pt`;
  }).join(', ');

  const alignments = columns.map(c => c.alignment || 'left').join(', ');

  const cellPadX = layoutMode === 'compact' ? '2.5pt' : layoutMode === 'presentation' ? '5pt' : '3pt';
  const cellPadY = layoutMode === 'compact' ? '1.5pt' : layoutMode === 'presentation' ? '3.5pt' : '1.9pt';

  lines.push('#table(');
  lines.push(`  columns: (${colWidths}),`);
  lines.push(`  align: (${alignments}),`);
  lines.push(`  inset: (x: ${cellPadX}, y: ${cellPadY}),`);
  lines.push(`  stroke: (x, y) => ${theme.tableStroke},`);
  lines.push(`  fill: (col, row) => if row == 0 { rgb("${theme.headerBackground}") } else if calc.even(row) { rgb("${theme.zebraBackground}") } else { none },`);

  // Table header row
  if (repeatHeaders) {
    lines.push('  table.header(');
    for (const col of columns) {
      lines.push(`    [#text(weight: "bold", fill: rgb("${theme.headerTextColor}"))[${escapeTypst(col.header)}]],`);
    }
    lines.push('  ),');
  } else {
    for (const col of columns) {
      lines.push(`  table.cell(fill: rgb("${theme.headerBackground}"))[#text(weight: "bold", fill: rgb("${theme.headerTextColor}"))[${escapeTypst(col.header)}]],`);
    }
  }

  // Table data rows
  for (const row of content.rows) {
    for (let cIdx = 0; cIdx < columns.length; cIdx++) {
      const cell = row.cells[cIdx];
      const val = cell ? cell.formattedValue : '';
      const escaped = escapeTypst(val);

      let cellContent = escaped;
      if (cell?.style?.bold) cellContent = `#text(weight: "bold")[${cellContent}]`;
      if (cell?.style?.italic) cellContent = `#text(style: "italic")[${cellContent}]`;
      if (cell?.style?.textColor) cellContent = `#text(fill: rgb("${cell.style.textColor}"))[${cellContent}]`;

      const alignAttr = cell?.alignment && cell.alignment !== columns[cIdx]?.alignment
        ? `align: ${cell.alignment}, `
        : '';

      if (cell?.style?.bgColor) {
        lines.push(`  table.cell(${alignAttr}fill: rgb("${cell.style.bgColor}"))[${cellContent}],`);
      } else if (alignAttr) {
        lines.push(`  table.cell(${alignAttr})[${cellContent}],`);
      } else {
        lines.push(`  [${cellContent}],`);
      }
    }
  }

  lines.push(')');
}

/**
 * Renders an explanatory notes / narrative text section.
 */
function renderTextSection(
  section: DocumentSection,
  theme: ThemeDefinition,
  lines: string[]
): void {
  const content = section.content as TextSectionContent;
  if (!content || !content.paragraphs || content.paragraphs.length === 0) return;

  if (section.title) {
    lines.push(`#heading(level: 2, numbering: none)[#text(size: 8.5pt, weight: "bold", fill: rgb("${theme.primaryColor}"))[${escapeTypst(section.title)}]]`);
    lines.push('#v(2pt)');
  }

  for (const para of content.paragraphs) {
    lines.push('#block(');
    lines.push('  width: 100%,');
    lines.push(`  fill: rgb("${theme.noteBackground}"),`);
    lines.push(`  stroke: (left: 2.5pt + rgb("${theme.noteBorderColor}")),`);
    lines.push('  inset: (x: 6pt, y: 3.5pt),');
    lines.push('  radius: (right: 3pt),');
    lines.push('  [');
    lines.push(`    #text(size: 7.2pt, fill: rgb("${theme.textColor}"))[${escapeTypst(para)}]`);
    lines.push('  ]');
    lines.push(')');
    lines.push('#v(1.5pt)');
  }
}
